---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
    app.kubernetes.io/name: deployment
    app.kubernetes.io/instance: controller-manager
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: turtles-etcd-restore
    app.kubernetes.io/part-of: turtles-etcd-restore
    app.kubernetes.io/managed-by: kustomize
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - command:
        - /manager
        args:
        - --leader-elect
        - --metrics-bind-addr=localhost:8080
        image: controller:latest
        name: manager
        ports:
        - containerPort: 9440
          name: healthz
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - "ALL"
          privileged: false
          runAsUser: 65532
          runAsGroup: 65532
        livenessProbe:
          httpGet:
            path: /healthz
            port: healthz
      terminationGracePeriodSeconds: 10
      serviceAccountName: controller-manager
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
        - effect: NoSchedule
          key: node-role.kubernetes.io/control-plane
