---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - turtles-capi.cattle.io
  resources:
  - etcdmachinebackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - turtles-capi.cattle.io
  resources:
  - etcdmachinebackups/finalizers
  verbs:
  - update
- apiGroups:
  - turtles-capi.cattle.io
  resources:
  - etcdmachinebackups/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - turtles-capi.cattle.io
  resources:
  - etcdsnapshots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - turtles-capi.cattle.io
  resources:
  - etcdsnapshots/finalizers
  verbs:
  - update
- apiGroups:
  - turtles-capi.cattle.io
  resources:
  - etcdsnapshots/status
  verbs:
  - get
  - patch
  - update
