apiVersion: v1
kind: Namespace
metadata:
  name: rke2-bootstrap-system
---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: BootstrapProvider
metadata:
  name: rke2
  namespace: rke2-bootstrap-system
spec:
  fetchConfig:
   url: "https://github.com/furkatgofurov7/cluster-api-provider-rke2/releases/v0.3.99/bootstrap-components.yaml"
---
apiVersion: v1
kind: Namespace
metadata:
  name: rke2-control-plane-system
---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: ControlPlaneProvider
metadata:
  name: rke2
  namespace: rke2-control-plane-system
spec:
  fetchConfig:
   url: "https://github.com/furkatgofurov7/cluster-api-provider-rke2/releases/v0.3.99/control-plane-components.yaml"